using System.Collections.Generic;

namespace CalendarService.Services
{
    public static class CalendarFolderMap
    {
        public static Dictionary<string,string> Ids = new Dictionary<string, string>
        {
            {"pmb", "AQMkADhmNjRiZThlLWRhNTMtNDc1Mi1iMTdiLWMzYWRiNjA0MGRjYQAuAAADcu1MvXIiXEqPpY8lNavH3gEAgi4wZCzjFkC9eoHZ1aeg6wAAAYqfXQAAAA==" },
            {"hgh", "AQMkADQ5YTFhMTRhLTNjZjktNDA0ZS04NmM3LWM2MmFjMGNmNGUwZAAuAAAD4qQNrrT+K025B0HcrHz6eAEAbQ0cvmuFcUe6lLTVni+FrAAAAgEOAAAA" },
            {"kmo", "AAMkADFiMzc2OTU0LTE0NjAtNDk5Ni04MDhmLTg0YWY1MzEzNGZhMQAuAAAAAABu3QaDFSNcQ5bS3UMl+QXVAQDH5+/3PrWATKMm/+iPEqcZAAAAgLBoAAA=" },
            {"bbu", "AQMkAGYyNTEwNjc2LWJhNDctNDJlNC05MDU0LTMwNTI0OGM2OGU3MQAuAAADyCvVfOYUmkq8WOQ88AVpuAEAWpt8TMFOU0ePAb+uArBCIgAAAgEOAAAA" },
            {"bha", "AAMkADE3ZGRiYmE5LTYzYTQtNGZhMC04MmQzLWMxMTU2ZDJjYmQ3YwAuAAAAAACd0raFn1xIRZ9W303ljuViAQCqtwGXXmFBQZu4qWENyCSIAAAAHGbWAAA=" },
            {"cni", "AQMkADk4YTdjMTg3LWRmOWUtNGQ3Ni04ZjY5LWFiODBiNmM4ZTM1YgAuAAADgA42SJfxf0S8FZ0MFzafaAEAwdjhR8TYykWE6KlEU7Y+YgAAAVHR9QAAAA==" },
            {"dgu", "AAMkADA3NWEzYWE1LTdjMTQtNDg3Ni04MzE3LTUxYWY4MDM4YTNjYwAuAAAAAACj7o67YVO+R42gY5lMNZiDAQCGl8j1f8ZaQYdMXhj6Wk7aAAAAmHkTAAA=" },
            {"dnb", "AQMkAGRkADNiMGNmMy1mZgE3LTRjMDEtODk2MS1lZQE2NGE1ZmU3NGQALgAAA+6U2zrrQ2NPkD7vQ/+LiSYBAPNcT49arGFAvC9wzq0LXrkAAAIBDgAAAA==" },
            {"hha", "AAMkAGFlZDdhOTM1LTg0MTktNDgzOC04ZTMwLTFmYzlhZDQxZWUyZAAuAAAAAADB9yZD5aIqSqqrJbLZVMCmAQB2bTZJraTQTZ4Y44laqzsEAAAAqkPuAAA=" },
            {"jus", "AAMkADhkMGRjZGVhLWFhMzUtNDgxYy05NjUxLTc5Y2FhNTg3NjYwYgAuAAAAAAAM0j/rQ5v4QIV602nFxSb0AQBhReWPUDm3TazGQxH5dLQZAAAAvyGMAAA=" },
            {"ksk", "AAMkAGM3OGYwZDc1LWU4MzctNDAwYy04Njk2LTMzM2U3ODVmM2I2YQAuAAAAAADuZtyGnhWGQK1C2D0dxSZuAQCBjfTYh1fyRJPDpHXNoIgBAAAAy5dRAAA=" },
            {"kso", "AAMkAGFhZTFhNmRlLTM2YTAtNGU0MS04ZGViLTMyY2JjZDY0YzhkOQAuAAAAAAA9xvQgzg6YRq2Rg+SzZP9rAQBSnv6dahOhS4u0iCycYUzTAAAAoA/uAAA=" },
            {"kbj", "AAMkADdlMzExNjA1LTYyOWUtNGNjNy1hNDUzLWVmNzlkOWJjYWU4ZAAuAAAAAAB4c4IZA75JTLFnomOVQ6pmAQBTjxJ4GREGSYhZGe2JJio0AAAAPkc4AAA=" },
            {"lcb", "AAMkADM4MWQzMTFkLTJiMGItNDUyOS1iNzg5LTAzMzg3N2Q4ZTdkYgAuAAAAAACi5xpOdVk3RrDsfkVJeYZqAQClZ3z0EmMaSJo+AgtvP6y1AAAAAAEOAAA=" },
            {"mud", "AAMkADJjNTNhZmQ4LTA1ZTAtNGQxZi1hMDNiLTZkNjAyZmZiZjMzYQAuAAAAAAA8m10dXgvGToXq6hpTn698AQBG7lY1h44cQpJeLfi8lwQLAAAA7xPLAAA=" },
            {"mbp", "AAMkADAzYmMyMmE1LWZjODctNDk0Yi04OTY3LWNmZjE2NDA0Y2E4ZQAuAAAAAABmBK0zEMLHRK9OgnR719QuAQA9FXZjQ6RWRJZTuLTq0Op7AAAAnCXWAAA=" },
            {"mha", "AQMkADBiYTU3NwFhLTFjMWUtNDcyOC1iOTc0LTVjNTkwMzQ2ZGU2YgAuAAAD3QfVe02tHk64ZlDjwmdh8AEAl0YcvHoTo0W/rL5MQEr/tAAAAUYQwwAAAA==" },
            {"mvs", "AQMkAGQxNTIxZWMyLTE2Y2EtNDk0Zi05OQA1ZC1kNWNmNmU2MTc4ZTgALgAAA/kuINSwonhCgHlf5VG+0rYBAI7/9IPOFjBHuuRpMWSC2BQAAAIBDgAAAA==" },
            {"mgo", "AAMkAGVmODRlZGIzLWM0NDQtNDdlMy05MmJjLWEyNjk5MGU1MmU4YwAuAAAAAACs+ksqnI5/Q7vxsqhi9bBTAQCI8fCxCpeTSYSzKgv33+h9AAAAudugAAA=" },
            {"psw", "AAMkAGMxZjEzNjg4LTliNTYtNDYzNi04OGQ3LTk3OGY0NGE1ZjhkMgAuAAAAAABtOpXZ/vVgTKR1/RkV1k6kAQD1CZls5EzDTKA+O1yVOugUAAAAdJCcAAA=" },
            {"pwe", "AQMkADc1ZDQ3NDY5LTg1ZGItNDI4MC05NDg5LWUzOGVmNzI1NjM4ZAAuAAADqLSQ0JxFWkafgF9zFBFg7QEAJ3udr+mFkkKvABxYJBWnQQAAAgEOAAAA" },
            {"shr", "AAMkADc4YWNjYmVmLWJmZGQtNGRlNi1iNzY3LTJmM2ZjYjRiMGE5OQAuAAAAAACUnk/MGY/MRIXaXuIaKAdsAQAwIvXM5gupS7PXZzqyFihUAAAAc811AAA=" },
            {"ssi", "AAMkADEyZjFlMTNjLTIzOTAtNDIyNi1hZTUyLTk2OWU0NmM4MjM2YgAuAAAAAADFE4X0Uh9KRZq4Fzqjw+UXAQCQeWMbNUOxRZLKIVvmlnOPAAAAz/N/AAA=" },
            {"jba", "AAMkAGM2ZWExMmI1LTllZWEtNGJiYi04YTQyLWI1OWE5ZTkzYWQyNQAuAAAAAAB/WIcxx2DhSIiLvICswzHiAQDV7iBStuuDQq4pDo6+larWAAAAv9YnAAA=" },
        };
    }
}
